version: "3"
services:
  traefik:
    image: traefik:2.2.8
    restart: always
    container_name: Traefik
    networks:
      - appnet
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    command: --api.insecure=true --providers.docker
    volumes:
      - ./conf/traefik/:/etc/traefik/
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
  nginx:
    image: nginx:1.19.2
    restart: always
    container_name: Nginx
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:hobr.site"
      - "traefik.frontend.entryPoints=https,http"
    networks:
      - appnet
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/nginx:/etc/nginx/conf.d
      - ./log/nginx:/var/log/nginx
      - ./www/:/var/www/html

networks:
  appnet:
    external: true
