version: "3"

  traefik:
    image: ./dockerfile/web/Traefik.Dockerfile
    restart: always
    container_name: Traefik
    networks:
      - appnet
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    environment:

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx:
    image: ./dockerfile/web/Nginx.Dockerfile
    restart: always
    container_name: Nginx
    networks:
      - appnet
    volumes:
      - /etc/localtime:/etc/localtime:ro

networks:
  appnet:
    external: true
